name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: deploy
        uses: youmengme/upload-lafyun@v0.0.7-test
        env:
            USER_ACCOUNT: ${{ secrets.LAF_ACCOUNT }}
            PASSWORD: ${{ secrets.LAF_PASSWORD }}
            REGION: ${{ secrets.LAF_REGION }}
            BUCKET: ${{ secrets.LAF_BUCKET }}
            ASSET_PATH: './docs'