on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Hello world action step
        id: hello
        uses: youmengme/upload-lafyun@v0.0.9-test
        env:
            USER_ACCOUNT: ${{ secrets.LAF_ACCOUNT }}
            PASSWORD: ${{ secrets.LAF_PASSWORD }}
            APPID: ${{ secrets.LAF_APPID }}
            REGION: ${{ secrets.LAF_REGION }}
            BUCKET: ${{ secrets.LAF_BUCKET }}
            ASSET_PATH: './docs'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"