on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@master
        
      # The following code is an example
      - name: deploy
        id: hello
        uses: youmengme/upload-lafyun@v1.0
        env:
            USER_ACCOUNT: ${{ secrets.LAF_ACCOUNT }}
            PASSWORD: ${{ secrets.LAF_PASSWORD }}
            APPID: ${{ secrets.LAF_APPID }}
            REGION: ${{ secrets.LAF_REGION }}
            BUCKET: ${{ secrets.LAF_BUCKET }}
            ASSET_PATH: './dist'
      # The code above is an example


      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"